version: "2"
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  rabbitmq:
    image: rabbitmq
  bridge:
    build:
      context: ..
      dockerfile: ./dockerfiles/bridge-develop.dockerfile
    ports:
      - '6382:6382'
    working_dir: '/bridge'
    command: /usr/bin/env node /bridge/bin/storj-bridge.js
    environment:
      NODE_ENV: 'develop'
#      LOG_LEVEL: 'info'
    volumes:
      - ..:/bridge
    links:
      - mongo
      - rabbitmq
#  ruby:
#    build:
#      context: ..
#      dockerfile: ./dockerfiles/ruby.dockerfile
#    working_dir: '/bridge'
#    command: ['/usr/bin/env', 'cucumber']
#    volumes:
#      - ..:/bridge
#    links:
#      - bridge
#      - mongo
